# Generated by Django 5.1.6 on 2025-02-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mode',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
