# Generated by Django 5.1.6 on 2025-02-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0002_alter_mode_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mode',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
